// Code generated by boundary1-conversion. DO NOT EDIT manually.
// See docs/boundary1-conversions.md for design details.

package hypershift

import (
	v1alpha1 "github.com/cdoan1/mono-repo/api/v1alpha1"
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ToHyperShiftHostedCluster converts a HyperFleet Cluster to a HyperShift HostedCluster.
//
// The conversion:
// 1. Maps passthrough fields directly (no type conversion needed)
// 2. Sets metadata (name, namespace, labels, annotations)
// 3. EXCLUDES envelope fields (deleteProtection, expirationTimestamp, properties, displayName)
//   - These are HyperFleet-only and not sent to HyperShift
//
// Note: OwnerReferences and finalizers should be set by the controller, not this function.
func ToHyperShiftHostedCluster(cluster *v1alpha1.Cluster) *hypershiftv1beta1.HostedCluster {
	if cluster == nil {
		return nil
	}

	hc := &hypershiftv1beta1.HostedCluster{
		ObjectMeta: metav1.ObjectMeta{
			Name:        cluster.Name,
			Namespace:   cluster.Namespace,
			Labels:      cluster.Labels,      // Merge/filter done by controller
			Annotations: cluster.Annotations, // Merge/filter done by controller
		},
	}

	// Map passthrough spec fields
	hc.Spec = toHyperShiftHostedClusterSpec(cluster.Spec.HostedCluster)

	return hc
}

// toHyperShiftHostedClusterSpec converts the passthrough spec.
//
// This is straightforward field mapping since HyperFleet's passthrough struct
// mirrors HyperShift's types exactly (generated from upstream).
//
// Note: We copy all fields from the passthrough struct. The passthrough type
// is generated to match HyperShift's HostedClusterSpec, so this is a 1:1 mapping.
func toHyperShiftHostedClusterSpec(spec v1alpha1.HostedClusterSpecPassthrough) hypershiftv1beta1.HostedClusterSpec {
	return hypershiftv1beta1.HostedClusterSpec{
		Release:                          spec.Release,
		ControlPlaneRelease:              spec.ControlPlaneRelease,
		ClusterID:                        spec.ClusterID,
		InfraID:                          spec.InfraID,
		UpdateService:                    spec.UpdateService,
		Channel:                          spec.Channel,
		Platform:                         spec.Platform,
		KubeAPIServerDNSName:             spec.KubeAPIServerDNSName,
		ControllerAvailabilityPolicy:     spec.ControllerAvailabilityPolicy,
		InfrastructureAvailabilityPolicy: spec.InfrastructureAvailabilityPolicy,
		DNS:                              spec.DNS,
		Networking:                       spec.Networking,
		Autoscaling:                      spec.Autoscaling,
		AutoNode:                         spec.AutoNode,
		Etcd:                             spec.Etcd,
		Services:                         spec.Services,
		PullSecret:                       spec.PullSecret,
		SSHKey:                           spec.SSHKey,
		IssuerURL:                        spec.IssuerURL,
		ServiceAccountSigningKey:         spec.ServiceAccountSigningKey,
		Configuration:                    spec.Configuration,
		ImageContentSources:              spec.ImageContentSources,
		AdditionalTrustBundle:            spec.AdditionalTrustBundle,
		SecretEncryption:                 spec.SecretEncryption,
		FIPS:                             spec.FIPS,
		PausedUntil:                      spec.PausedUntil,
		OLMCatalogPlacement:              spec.OLMCatalogPlacement,
		OperatorConfiguration:            spec.OperatorConfiguration,
		AuditWebhook:                     spec.AuditWebhook,
		NodeSelector:                     spec.NodeSelector,
		Tolerations:                      spec.Tolerations,
	}
}

// FromHyperShiftHostedCluster extracts status from a HyperShift HostedCluster.
//
// The conversion:
// 1. Reads HyperShift status fields
// 2. Maps to HyperFleet status format
// 3. DOES NOT touch envelope fields (controller manages those separately)
//
// Note: Currently maps to the simplified ClusterStatus.
// In production, this would map to a HostedClusterStatusPassthrough type.
func FromHyperShiftHostedCluster(hc *hypershiftv1beta1.HostedCluster) v1alpha1.ClusterStatus {
	if hc == nil {
		return v1alpha1.ClusterStatus{}
	}

	status := v1alpha1.ClusterStatus{}

	// Map version information
	if hc.Status.Version != nil {
		status.Version = hc.Status.Version.Desired.Version
	}

	// Map conditions
	// Note: HyperShift uses its own condition type, we'd need to convert
	// For now, we'll create simplified conditions
	for _, hcCond := range hc.Status.Conditions {
		status.Conditions = append(status.Conditions, metav1.Condition{
			Type:               hcCond.Type,
			Status:             metav1.ConditionStatus(hcCond.Status),
			LastTransitionTime: hcCond.LastTransitionTime,
			Reason:             hcCond.Reason,
			Message:            hcCond.Message,
		})
	}

	// Map high-level state from conditions
	// This is a simplified heuristic - production would be more sophisticated
	status.State = computeClusterState(hc.Status.Conditions)

	return status
}

// computeClusterState derives high-level state from HyperShift conditions.
//
// This is a simplified heuristic for POC purposes.
// Production implementation would have more sophisticated logic.
//
// Priority order: Available > Degraded > Progressing > default (pending)
func computeClusterState(conditions []metav1.Condition) string {
	if len(conditions) == 0 {
		return "pending"
	}

	// Check conditions in priority order
	// 1. Available=True means cluster is ready (highest priority)
	for _, cond := range conditions {
		if cond.Type == "Available" && cond.Status == "True" {
			return "ready"
		}
	}

	// 2. Degraded=True means cluster has issues
	for _, cond := range conditions {
		if cond.Type == "Degraded" && cond.Status == "True" {
			return "degraded"
		}
	}

	// 3. Progressing=True means cluster is being provisioned/updated
	for _, cond := range conditions {
		if cond.Type == "Progressing" && cond.Status == "True" {
			return "provisioning"
		}
	}

	return "pending"
}
