// Code generated by boundary1-conversion. DO NOT EDIT manually.
// See docs/boundary1-conversions.md for design details.

package hypershift

import (
	v1alpha1 "github.com/cdoan1/mono-repo/api/v1alpha1"
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ToHyperShiftNodePool converts a HyperFleet NodePool to a HyperShift NodePool.
//
// The conversion:
// 1. Maps passthrough fields directly
// 2. Sets metadata (name, namespace, labels, annotations)
// 3. EXCLUDES envelope fields (clusterRef, displayName, autoRepair)
//    - These are HyperFleet-only and not sent to HyperShift
//
// Note: OwnerReferences should be set by the controller to reference the HostedCluster.
func ToHyperShiftNodePool(np *v1alpha1.NodePool) *hypershiftv1beta1.NodePool {
	if np == nil {
		return nil
	}

	hsnp := &hypershiftv1beta1.NodePool{
		ObjectMeta: metav1.ObjectMeta{
			Name:        np.Name,
			Namespace:   np.Namespace,
			Labels:      np.Labels,
			Annotations: np.Annotations,
		},
	}

	// Map passthrough spec
	hsnp.Spec = toHyperShiftNodePoolSpec(np.Spec.NodePool)

	return hsnp
}

// toHyperShiftNodePoolSpec converts the passthrough NodePool spec.
//
// This is straightforward field mapping since HyperFleet's passthrough struct
// mirrors HyperShift's NodePoolSpec exactly (generated from upstream).
func toHyperShiftNodePoolSpec(spec v1alpha1.NodePoolSpecPassthrough) hypershiftv1beta1.NodePoolSpec {
	return hypershiftv1beta1.NodePoolSpec{
		ClusterName:             spec.ClusterName,
		Release:                 spec.Release,
		Platform:                spec.Platform,
		Replicas:                spec.Replicas,
		Management:              spec.Management,
		AutoScaling:             spec.AutoScaling,
		Config:                  spec.Config,
		NodeDrainTimeout:        spec.NodeDrainTimeout,
		NodeVolumeDetachTimeout: spec.NodeVolumeDetachTimeout,
		NodeLabels:              spec.NodeLabels,
		Taints:                  spec.Taints,
		PausedUntil:             spec.PausedUntil,
		TuningConfig:            spec.TuningConfig,
		Arch:                    spec.Arch,
	}
}

// FromHyperShiftNodePool extracts status from a HyperShift NodePool.
//
// The conversion:
// 1. Reads HyperShift NodePool status
// 2. Maps to HyperFleet NodePoolStatus format
// 3. DOES NOT touch envelope fields (controller manages those)
//
// Note: Currently maps to the simplified NodePoolStatus.
// In production, this would map to a NodePoolStatusPassthrough type.
func FromHyperShiftNodePool(np *hypershiftv1beta1.NodePool) v1alpha1.NodePoolStatus {
	if np == nil {
		return v1alpha1.NodePoolStatus{}
	}

	status := v1alpha1.NodePoolStatus{}

	// Map replica information
	status.Replicas = np.Status.Replicas

	// Map conditions (convert from HyperShift NodePoolCondition to K8s Condition)
	for _, npCond := range np.Status.Conditions {
		status.Conditions = append(status.Conditions, metav1.Condition{
			Type:               npCond.Type,
			Status:             metav1.ConditionStatus(npCond.Status),
			LastTransitionTime: npCond.LastTransitionTime,
			Reason:             npCond.Reason,
			Message:            npCond.Message,
		})
	}

	// Map high-level state from conditions
	status.State = computeNodePoolState(status.Conditions)

	return status
}

// computeNodePoolState derives high-level state from HyperShift NodePool conditions.
//
// This is a simplified heuristic for POC purposes.
// Production implementation would have more sophisticated logic.
//
// Priority order: Ready > AllNodesHealthy (unhealthy) > UpdatingVersion > default (pending)
func computeNodePoolState(conditions []metav1.Condition) string {
	if len(conditions) == 0 {
		return "pending"
	}

	// Check conditions in priority order
	// 1. Ready=True means nodepool is ready (highest priority)
	for _, cond := range conditions {
		if cond.Type == "Ready" && cond.Status == "True" {
			return "ready"
		}
	}

	// 2. AllNodesHealthy=False means nodepool has unhealthy nodes
	for _, cond := range conditions {
		if cond.Type == "AllNodesHealthy" && cond.Status == "False" {
			return "degraded"
		}
	}

	// 3. UpdatingVersion=True means nodepool is updating
	for _, cond := range conditions {
		if cond.Type == "UpdatingVersion" && cond.Status == "True" {
			return "updating"
		}
	}

	return "pending"
}
