// Code generated by conversion-gen. DO NOT EDIT.

package rest

// ClusterReference identifies the parent cluster
type ClusterReference struct {
	// Name is the name of the Cluster resource
	// +kubebuilder:validation:Required
	Name string `json:"name"`
	// Namespace is the namespace of the Cluster resource
	// If empty, defaults to the same namespace as this NodePool
	Namespace string `json:"namespace,omitempty"`
}
