// Code generated by conversion-gen. DO NOT EDIT.

package rest

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ClusterSpec defines the desired state of a Cluster
type ClusterSpec struct {
	// DisplayName is a human-readable name for the cluster
	// +hyperfleet:write-mode=mutable
	// +kubebuilder:validation:MaxLength=256
	DisplayName string `json:"displayName,omitempty"`
	// DeleteProtection prevents accidental deletion when enabled
	// +hyperfleet:write-mode=mutable
	DeleteProtection *bool `json:"deleteProtection,omitempty"`
	// ExpirationTimestamp marks when this cluster should be automatically deleted
	// +hyperfleet:write-mode=mutable
	ExpirationTimestamp *metav1.Time `json:"expirationTimestamp,omitempty"`
	// Properties are arbitrary key-value pairs for customer metadata
	// +hyperfleet:write-mode=mutable
	Properties map[string]string `json:"properties,omitempty"`
	// Tags are customer-defined labels for organizational purposes
	// This is a TechPreview feature
	// +hyperfleet:write-mode=mutable
	// +openshift:enable:FeatureGate=HyperFleetAutoScaling
	Tags map[string]string `json:"tags,omitempty"`
	// HostedCluster contains the full HyperShift HostedCluster configuration
	// All fields are generated from upstream and have safe defaults (hidden + service-set)
	// until explicitly reviewed and exposed
	// +kubebuilder:validation:Required
	HostedCluster HostedClusterSpecPassthrough `json:"hostedCluster"`
}
