// Code generated by conversion-gen. DO NOT EDIT.

package rest

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ClusterStatus defines the observed state of a Cluster
type ClusterStatus struct {
	// State represents the high-level cluster state
	// +kubebuilder:validation:Enum=pending;provisioning;ready;degraded;deleting;failed
	State string `json:"state,omitempty"`
	// Conditions represent detailed cluster status
	Conditions []metav1.Condition `json:"conditions,omitempty"`
	// Version is the observed OpenShift version
	Version string `json:"version,omitempty"`
	// APIEndpoint is the cluster API server endpoint
	APIEndpoint string `json:"apiEndpoint,omitempty"`
	// ConsoleURL is the web console URL
	ConsoleURL string `json:"consoleUrl,omitempty"`
	// ProvisionStartTime is when provisioning began
	ProvisionStartTime *metav1.Time `json:"provisionStartTime,omitempty"`
	// ReadyTime is when the cluster became ready
	ReadyTime *metav1.Time `json:"readyTime,omitempty"`
}
