// Code generated by conversion-gen. DO NOT EDIT.

package rest

// Cluster represents a HyperFleet managed OpenShift cluster
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced
type Cluster struct {
	Spec ClusterSpec `json:"spec"`
	Status ClusterStatus `json:"status,omitempty"`
}
