// Code generated by conversion-gen. DO NOT EDIT.

package rest

// NodePool represents a HyperFleet managed NodePool for a cluster
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced
type NodePool struct {
	Spec NodePoolSpec `json:"spec"`
	Status NodePoolStatus `json:"status,omitempty"`
}
