// Code generated by conversion-gen. DO NOT EDIT.

package rest

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NodePoolStatus defines the observed state of a NodePool
type NodePoolStatus struct {
	// State represents the high-level node pool state
	// +kubebuilder:validation:Enum=pending;scaling;ready;degraded;deleting;failed
	State string `json:"state,omitempty"`
	// Conditions represent detailed node pool status
	Conditions []metav1.Condition `json:"conditions,omitempty"`
	// Replicas is the current number of nodes
	Replicas int32 `json:"replicas,omitempty"`
	// ReadyReplicas is the number of ready nodes
	ReadyReplicas int32 `json:"readyReplicas,omitempty"`
	// AvailableReplicas is the number of available nodes
	AvailableReplicas int32 `json:"availableReplicas,omitempty"`
}
