// Code generated by conversion-gen. DO NOT EDIT.

package rest

// NodePoolSpec defines the desired state of a NodePool
type NodePoolSpec struct {
	// ClusterRef references the parent Cluster
	// +kubebuilder:validation:Required
	ClusterRef ClusterReference `json:"clusterRef"`
	// DisplayName is a human-readable name for the node pool
	// +hyperfleet:write-mode=mutable
	DisplayName string `json:"displayName,omitempty"`
	// AutoRepair enables automatic repair of unhealthy nodes
	// +hyperfleet:write-mode=mutable
	AutoRepair *bool `json:"autoRepair,omitempty"`
	// Labels to apply to nodes in this pool
	// +hyperfleet:write-mode=mutable
	Labels map[string]string `json:"labels,omitempty"`
	// NodePool contains the full HyperShift NodePool configuration
	// All fields are generated from upstream and have safe defaults (hidden + service-set)
	// +kubebuilder:validation:Required
	NodePool NodePoolSpecPassthrough `json:"nodePool"`
}
