// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cdoan1/mono-repo/api/v1alpha1"
	"github.com/cdoan1/mono-repo/tools/pkg/conversion"
	"github.com/cdoan1/mono-repo/tools/pkg/conversion/v1alpha1/rest"
)

// ProjectCluster converts CRD Cluster to REST (visible fields only)
func ProjectCluster(crd *v1alpha1.Cluster) *rest.Cluster {
	if crd == nil {
		return nil
	}

	return &rest.Cluster{
		Spec:   projectClusterSpec(crd.Spec),
		Status: projectClusterStatus(crd.Status),
	}
}

// projectClusterSpec converts CRD ClusterSpec to REST
func projectClusterSpec(crd v1alpha1.ClusterSpec) rest.ClusterSpec {
	return rest.ClusterSpec{
		DisplayName: crd.DisplayName,
		DeleteProtection: crd.DeleteProtection,
		ExpirationTimestamp: crd.ExpirationTimestamp,
		Properties: crd.Properties,
		Tags: crd.Tags,
		HostedCluster: projectHostedClusterSpecPassthrough(crd.HostedCluster),
	}
}

// projectClusterStatus converts CRD ClusterStatus to REST
func projectClusterStatus(crd v1alpha1.ClusterStatus) rest.ClusterStatus {
	return rest.ClusterStatus{
		State: crd.State,
		Conditions: crd.Conditions,
		Version: crd.Version,
		APIEndpoint: crd.APIEndpoint,
		ConsoleURL: crd.ConsoleURL,
		ProvisionStartTime: crd.ProvisionStartTime,
		ReadyTime: crd.ReadyTime,
	}
}

// UnprojectCluster converts REST ClusterSpec to CRD with service-set enrichment
func UnprojectCluster(spec *rest.ClusterSpec, enrichment *conversion.ServiceSetFields) *v1alpha1.ClusterSpec {
	if spec == nil {
		return nil
	}

	crdSpec := &v1alpha1.ClusterSpec{
		// Visible fields from REST request
		DisplayName: spec.DisplayName,
		DeleteProtection: spec.DeleteProtection,
		ExpirationTimestamp: spec.ExpirationTimestamp,
		Properties: spec.Properties,
		Tags: spec.Tags,
		HostedCluster: unprojectHostedClusterSpecPassthrough(spec.HostedCluster),
	}

	// Service-set fields from platform enrichment
	if enrichment != nil {
		crdSpec.AccountID = enrichment.AccountID
		crdSpec.CreatorARN = enrichment.CreatorARN
		crdSpec.InternalID = enrichment.InternalID
	}

	return crdSpec
}

// projectHostedClusterSpecPassthrough converts CRD type to REST
func projectHostedClusterSpecPassthrough(crd v1alpha1.HostedClusterSpecPassthrough) rest.HostedClusterSpecPassthrough {
	return rest.HostedClusterSpecPassthrough{
		Channel: crd.Channel,
		AutoNode: crd.AutoNode,
		Configuration: ConvertClusterConfiguration_v1beta1_to_v1alpha1(crd.Configuration),
		OperatorConfiguration: crd.OperatorConfiguration,
		FIPS: crd.FIPS,
		PausedUntil: crd.PausedUntil,
	}
}

// unprojectHostedClusterSpecPassthrough converts REST type to CRD
func unprojectHostedClusterSpecPassthrough(rest rest.HostedClusterSpecPassthrough) v1alpha1.HostedClusterSpecPassthrough {
	return v1alpha1.HostedClusterSpecPassthrough{
		Channel: rest.Channel,
		AutoNode: rest.AutoNode,
		Configuration: ConvertClusterConfiguration_v1alpha1_to_v1beta1(rest.Configuration),
		OperatorConfiguration: rest.OperatorConfiguration,
		FIPS: rest.FIPS,
		PausedUntil: rest.PausedUntil,
	}
}

