// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"

	v1alpha1 "github.com/cdoan1/mono-repo/api/v1alpha1"
	v1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
)

// ConvertClusterConfiguration_v1alpha1_to_v1beta1 converts HyperFleet's mirror Configuration to HyperShift's upstream type
//
// This function is automatically generated when a mirror type mapping exists for the Configuration field.
// It enables conversion between HyperFleet-owned types (with granular markers) and HyperShift upstream types.
//
// Uses JSON round-trip for automatic field mapping:
// - Simple implementation that doesn't require field-by-field code
// - Works for most cases where field names/types match
// - Handles nested struct conversions automatically
// - Loses unexported fields (not an issue for our public API types)
func ConvertClusterConfiguration_v1alpha1_to_v1beta1(in *v1alpha1.ClusterConfiguration) *v1beta1.ClusterConfiguration {
	if in == nil {
		return nil
	}

	// JSON round-trip: marshal our type, unmarshal to theirs
	data, err := json.Marshal(in)
	if err != nil {
		// In a real implementation, this should be logged or returned as an error
		// For now, return nil to avoid panics
		return nil
	}

	out := &v1beta1.ClusterConfiguration{}
	if err := json.Unmarshal(data, out); err != nil {
		return nil
	}

	return out
}

// ConvertClusterConfiguration_v1beta1_to_v1alpha1 converts HyperShift's upstream Configuration to HyperFleet's mirror type
//
// This is the reverse conversion - used when reading from HyperShift and projecting to REST API.
func ConvertClusterConfiguration_v1beta1_to_v1alpha1(in *v1beta1.ClusterConfiguration) *v1alpha1.ClusterConfiguration {
	if in == nil {
		return nil
	}

	// JSON round-trip: marshal their type, unmarshal to ours
	data, err := json.Marshal(in)
	if err != nil {
		return nil
	}

	out := &v1alpha1.ClusterConfiguration{}
	if err := json.Unmarshal(data, out); err != nil {
		return nil
	}

	return out
}

// ConvertAutoNode_value_to_pointer handles AutoNode type change from value to pointer
//
// HyperShift v0.1.78 changed AutoNode from *AutoNode (pointer) to AutoNode (value).
// This function converts a value type to a pointer, checking for zero values.
func ConvertAutoNode_value_to_pointer(in v1beta1.AutoNode) *v1beta1.AutoNode {
	// If zero value, return nil (equivalent to missing field)
	if in == (v1beta1.AutoNode{}) {
		return nil
	}
	// Otherwise, return pointer to the value
	return &in
}

// ConvertAutoNode_pointer_to_value handles AutoNode type change from pointer to value
//
// This is the reverse conversion - pointer to value.
func ConvertAutoNode_pointer_to_value(in *v1beta1.AutoNode) v1beta1.AutoNode {
	if in == nil {
		return v1beta1.AutoNode{} // Return zero value if nil
	}
	return *in // Dereference pointer
}
