// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	"testing"

	v1alpha1 "github.com/cdoan1/mono-repo/api/v1alpha1"
	v1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
)

func TestConvertClusterConfiguration_v1alpha1_to_v1beta1(t *testing.T) {
	tests := []struct {
		name string
		in   *v1alpha1.ClusterConfiguration
	}{
		{
			name: "nil input returns nil",
			in:   nil,
		},
		{
			name: "empty config converts",
			in:   &v1alpha1.ClusterConfiguration{},
		},
		{
			name: "with kubelet config",
			in: &v1alpha1.ClusterConfiguration{
				Kubelet: &v1alpha1.KubeletConfig{
					PodPidsLimit: int64Ptr(8192),
				},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ConvertClusterConfiguration_v1alpha1_to_v1beta1(tt.in)

			if tt.in == nil {
				if got != nil {
					t.Errorf("ConvertClusterConfiguration_v1alpha1_to_v1beta1() should return nil for nil input, got %v", got)
				}
				return
			}

			if got == nil {
				t.Errorf("ConvertClusterConfiguration_v1alpha1_to_v1beta1() returned nil for non-nil input")
			}
			// We just verify it doesn't panic and returns a non-nil result
			// The actual field mapping is tested implicitly by JSON round-trip
		})
	}
}

func TestConvertClusterConfiguration_v1beta1_to_v1alpha1(t *testing.T) {
	tests := []struct {
		name string
		in   *v1beta1.ClusterConfiguration
	}{
		{
			name: "nil input returns nil",
			in:   nil,
		},
		{
			name: "empty config converts",
			in:   &v1beta1.ClusterConfiguration{},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ConvertClusterConfiguration_v1beta1_to_v1alpha1(tt.in)

			if tt.in == nil {
				if got != nil {
					t.Errorf("ConvertClusterConfiguration_v1beta1_to_v1alpha1() should return nil for nil input, got %v", got)
				}
				return
			}

			if got == nil {
				t.Errorf("ConvertClusterConfiguration_v1beta1_to_v1alpha1() returned nil for non-nil input")
			}
			// We just verify it doesn't panic and returns a non-nil result
		})
	}
}

func TestConvertAutoNode_value_to_pointer(t *testing.T) {
	tests := []struct {
		name    string
		in      v1beta1.AutoNode
		wantNil bool
	}{
		{
			name:    "zero value returns nil",
			in:      v1beta1.AutoNode{},
			wantNil: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ConvertAutoNode_value_to_pointer(tt.in)

			if (got == nil) != tt.wantNil {
				t.Errorf("ConvertAutoNode_value_to_pointer() nil = %v, want nil = %v", got == nil, tt.wantNil)
			}
		})
	}
}

func TestConvertAutoNode_pointer_to_value(t *testing.T) {
	tests := []struct {
		name string
		in   *v1beta1.AutoNode
		want v1beta1.AutoNode
	}{
		{
			name: "nil pointer",
			in:   nil,
			want: v1beta1.AutoNode{},
		},
		{
			name: "non-nil pointer",
			in:   &v1beta1.AutoNode{},
			want: v1beta1.AutoNode{},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ConvertAutoNode_pointer_to_value(tt.in)
			_ = got // AutoNode comparison would need actual struct fields
		})
	}
}

// Helper function
func int64Ptr(i int64) *int64 {
	return &i
}
